server:
  port: 8080

spring:
  rabbitmq:
    addresses: 192.168.101.65
    port: 5672
    username: njauwj
    password: 1724031211
    virtual-host: my_virtual_host
    listener:
      simple:
        acknowledge-mode: manual #设置手动接受消息
    publisher-confirm-type: correlated
    publisher-returns: true
test:
  name: wj
